apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tce-ltpa.fullname" . }}
  labels:
    {{- include "tce-ltpa.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
