{{- if .Values.flaskSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flaskSecret.name | default (printf "%s-flask" (include "tce-ltpa.fullname" .)) }}
  labels:
    {{- include "tce-ltpa.labels" . | nindent 4 }}
stringData:
  {{ .Values.flaskSecret.key }}: {{ .Values.flaskSecret.value | quote }}
{{- end }}
